stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/insurance.csv
    outs:
    - data/raw/insurance.csv
  
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/insurance.csv
    outs:
    - data/processed/train_insurance.csv
    - data/processed/test_insurance.csv
  
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_insurance.csv
    - data/processed/test_insurance.csv
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.max_depth
    - estimators.RandomForestRegressor.params.max_leaf_nodes
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false

    outs:
    - saved_models/model.joblib








